version: '3.8'

services:
  gama-fit:
    build: .
    container_name: gama-fit-app
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=/app/internal/data/gamafit.db
    volumes:
      - ./data:/app/internal/data
    restart: unless-stopped
